name: 🐛 Bug Report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I try to..., the app crashes...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of react-native-console-modal are you using?
      placeholder: e.g., 0.1.2
    validations:
      required: true

  - type: input
    id: rn-version
    attributes:
      label: React Native Version
      description: What version of React Native are you using?
      placeholder: e.g., 0.72.0
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Which platforms are affected?
      multiple: true
      options:
        - iOS
        - Android
        - Both
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
